//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnt.Panacea.Xap.Odontologia.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cnt.Panacea.Xap.Odontologia.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandonado.
        /// </summary>
        public static string Abandonado {
            get {
                return ResourceManager.GetString("Abandonado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acepto.
        /// </summary>
        public static string Acepto {
            get {
                return ResourceManager.GetString("Acepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjuntar imágenes.
        /// </summary>
        public static string Adjuntar_Imagenes {
            get {
                return ResourceManager.GetString("Adjuntar_Imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        public static string Aplicar {
            get {
                return ResourceManager.GetString("Aplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar a.
        /// </summary>
        public static string Aplicar_a {
            get {
                return ResourceManager.GetString("Aplicar_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar procedimientos.
        /// </summary>
        public static string Aplicar_Procedimientos {
            get {
                return ResourceManager.GetString("Aplicar_Procedimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea aprobar la cotización.
        /// </summary>
        public static string Aprobar_Cotizacion {
            get {
                return ResourceManager.GetString("Aprobar_Cotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo salvado.
        /// </summary>
        public static string Archivo_Salvado {
            get {
                return ResourceManager.GetString("Archivo_Salvado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrás.
        /// </summary>
        public static string Atras {
            get {
                return ResourceManager.GetString("Atras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aumentar.
        /// </summary>
        public static string Aumentar {
            get {
                return ResourceManager.GetString("Aumentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boca.
        /// </summary>
        public static string Boca {
            get {
                return ResourceManager.GetString("Boca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodega.
        /// </summary>
        public static string Bodega {
            get {
                return ResourceManager.GetString("Bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar convenio.
        /// </summary>
        public static string Cambiar_Convenio {
            get {
                return ResourceManager.GetString("Cambiar_Convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambios sin guardar.
        /// </summary>
        public static string Cambios {
            get {
                return ResourceManager.GetString("Cambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sistema ha identificado que ha realizado cambios que aun no se han guardado. ¿Desea continuar?.
        /// </summary>
        public static string Cambios_No_Guardados {
            get {
                return ResourceManager.GetString("Cambios_No_Guardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen campos sin diligenciar.
        /// </summary>
        public static string Campos_Sin_Diligenciar {
            get {
                return ResourceManager.GetString("Campos_Sin_Diligenciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        public static string Clave {
            get {
                return ResourceManager.GetString("Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De clic en siguiente por favor.
        /// </summary>
        public static string Click_Siguiente {
            get {
                return ResourceManager.GetString("Click_Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobro.
        /// </summary>
        public static string Cobro {
            get {
                return ResourceManager.GetString("Cobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un comprobante para la cotización.
        /// </summary>
        public static string Comprobante_Cotizacion {
            get {
                return ResourceManager.GetString("Comprobante_Cotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta.
        /// </summary>
        public static string Consulta {
            get {
                return ResourceManager.GetString("Consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string Continuar {
            get {
                return ResourceManager.GetString("Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenio.
        /// </summary>
        public static string Convenio {
            get {
                return ResourceManager.GetString("Convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotización.
        /// </summary>
        public static string Cotizacion {
            get {
                return ResourceManager.GetString("Cotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubre convenio.
        /// </summary>
        public static string Cubre_Convenio {
            get {
                return ResourceManager.GetString("Cubre_Convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuota inicial.
        /// </summary>
        public static string Cuota_Inicial {
            get {
                return ResourceManager.GetString("Cuota_Inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen datos asociados que aún no se han cargado por favor navegue a la pestana de plan de tratamiento y después al plan de evolución..
        /// </summary>
        public static string Datos_Odontograma_Evolucion {
            get {
                return ResourceManager.GetString("Datos_Odontograma_Evolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir plan tratamiento.
        /// </summary>
        public static string Definir_Plan_Tratamiento {
            get {
                return ResourceManager.GetString("Definir_Plan_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        public static string Descargar {
            get {
                return ResourceManager.GetString("Descargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshacer.
        /// </summary>
        public static string Deshacer {
            get {
                return ResourceManager.GetString("Deshacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este diagnóstico o procedimiento ya se encuentra asociado a este elemento.
        /// </summary>
        public static string Diagnostico_Procedimiento_Asignado {
            get {
                return ResourceManager.GetString("Diagnostico_Procedimiento_Asignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnósticos.
        /// </summary>
        public static string Diagnosticos {
            get {
                return ResourceManager.GetString("Diagnosticos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen diagnósticos sin procedimiento asociado.
        /// </summary>
        public static string Diagnosticos_Sin_Procedimiento_Asociado {
            get {
                return ResourceManager.GetString("Diagnosticos_Sin_Procedimiento_Asociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Diente {
            get {
                return ResourceManager.GetString("Diente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diente.
        /// </summary>
        public static string Dientes {
            get {
                return ResourceManager.GetString("Dientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supera la cantidad de procedimientos en la sesión.
        /// </summary>
        public static string Error_Cantidad_Procedimientos {
            get {
                return ResourceManager.GetString("Error_Cantidad_Procedimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supera la cantidad de sesiones.
        /// </summary>
        public static string Error_Cantidad_Sesiones {
            get {
                return ResourceManager.GetString("Error_Cantidad_Sesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De clic en siguiente antes de guardar.
        /// </summary>
        public static string Error_Elementos_PlanTratamiento {
            get {
                return ResourceManager.GetString("Error_Elementos_PlanTratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La imagen seleccionada presenta errores.
        /// </summary>
        public static string Error_Imagen {
            get {
                return ResourceManager.GetString("Error_Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de piezas debe ser un dato númerico mayor de 0.
        /// </summary>
        public static string Error_Mensaje_Piezas {
            get {
                return ResourceManager.GetString("Error_Mensaje_Piezas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El numero de dientes no puede ser negativo.
        /// </summary>
        public static string Error_Mensaje_Piezas2 {
            get {
                return ResourceManager.GetString("Error_Mensaje_Piezas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No esta cubierto por el convenio.
        /// </summary>
        public static string Error_No_Cubre_Convenio1 {
            get {
                return ResourceManager.GetString("Error_No_Cubre_Convenio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro :.
        /// </summary>
        public static string Error_No_Cubre_Convenio2 {
            get {
                return ResourceManager.GetString("Error_No_Cubre_Convenio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las sesiones no están configuradas correctamente.
        /// </summary>
        public static string Error_Sesiones {
            get {
                return ResourceManager.GetString("Error_Sesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las sesiones deben asignarse consecutivamente.
        /// </summary>
        public static string Error_Sesiones_Consecutivas {
            get {
                return ResourceManager.GetString("Error_Sesiones_Consecutivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No podrá realizar ninguna acción en el odontograma de tratamiento hasta que tenga diagnósticos en el odontograma inicial.
        /// </summary>
        public static string Error_Solo_Procedimientos {
            get {
                return ResourceManager.GetString("Error_Solo_Procedimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la especialidad a cada procedimiento..
        /// </summary>
        public static string ErrorEspecialidad {
            get {
                return ResourceManager.GetString("ErrorEspecialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidad.
        /// </summary>
        public static string Especialidad {
            get {
                return ResourceManager.GetString("Especialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado del tratamiento.
        /// </summary>
        public static string Estado_Tratamiento {
            get {
                return ResourceManager.GetString("Estado_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        public static string Factura {
            get {
                return ResourceManager.GetString("Factura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha final.
        /// </summary>
        public static string Fecha_Final {
            get {
                return ResourceManager.GetString("Fecha_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inicial.
        /// </summary>
        public static string Fecha_Inicial {
            get {
                return ResourceManager.GetString("Fecha_Inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inicio.
        /// </summary>
        public static string Fecha_Inicio_Tratamiento {
            get {
                return ResourceManager.GetString("Fecha_Inicio_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalidad.
        /// </summary>
        public static string Finalidad_Procedimiento {
            get {
                return ResourceManager.GetString("Finalidad_Procedimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizado.
        /// </summary>
        public static string Finalizado {
            get {
                return ResourceManager.GetString("Finalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar tratamiento.
        /// </summary>
        public static string Finalizar_Tratamiento {
            get {
                return ResourceManager.GetString("Finalizar_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de pago.
        /// </summary>
        public static string Forma_Pago {
            get {
                return ResourceManager.GetString("Forma_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se genera el plan de tratamiento No..
        /// </summary>
        public static string Genero_Plan_Tratamiento1 {
            get {
                return ResourceManager.GetString("Genero_Plan_Tratamiento1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de tratamiento.
        /// </summary>
        public static string Genero_Plan_Tratamiento2 {
            get {
                return ResourceManager.GetString("Genero_Plan_Tratamiento2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ortodoncia.
        /// </summary>
        public static string Genero_Plan_Tratamiento3 {
            get {
                return ResourceManager.GetString("Genero_Plan_Tratamiento3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se genera cotización No..
        /// </summary>
        public static string Genero_Plan_Tratamiento4 {
            get {
                return ResourceManager.GetString("Genero_Plan_Tratamiento4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar en el equipo.
        /// </summary>
        public static string Guardar_Equipo {
            get {
                return ResourceManager.GetString("Guardar_Equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontograma guardado correctamente.
        /// </summary>
        public static string Guardar_Odontograma {
            get {
                return ResourceManager.GetString("Guardar_Odontograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higienista.
        /// </summary>
        public static string Higienista {
            get {
                return ResourceManager.GetString("Higienista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial odontograma.
        /// </summary>
        public static string Historial_Odontograma {
            get {
                return ResourceManager.GetString("Historial_Odontograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        public static string Imagen {
            get {
                return ResourceManager.GetString("Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontograma inicial.
        /// </summary>
        public static string Imprimir_Odontograma_Inicial {
            get {
                return ResourceManager.GetString("Imprimir_Odontograma_Inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontograma plan de tratamiento.
        /// </summary>
        public static string Imprimir_Odontograma_Plan_Tratamiento {
            get {
                return ResourceManager.GetString("Imprimir_Odontograma_Plan_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informes.
        /// </summary>
        public static string Informes {
            get {
                return ResourceManager.GetString("Informes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insumos.
        /// </summary>
        public static string Insumos {
            get {
                return ResourceManager.GetString("Insumos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere una justificación para guardar en el sistema..
        /// </summary>
        public static string Justificacion_Guardar_Sistema {
            get {
                return ResourceManager.GetString("Justificacion_Guardar_Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo número de procedimientos por sesión.
        /// </summary>
        public static string Maximo_Procedimientos_Por_Sesion {
            get {
                return ResourceManager.GetString("Maximo_Procedimientos_Por_Sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden realizar mas procedimientos en esta sesión.
        /// </summary>
        public static string Maximo_Procedimientos_Sesion {
            get {
                return ResourceManager.GetString("Maximo_Procedimientos_Sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede insertar máximo 10 piezas dentales supernumerarias.
        /// </summary>
        public static string Maximo_Supernumerarios {
            get {
                return ResourceManager.GetString("Maximo_Supernumerarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este procedimiento no se encuentra cubierto por el convenio.
        /// </summary>
        public static string Mensaje_Convenio {
            get {
                return ResourceManager.GetString("Mensaje_Convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta fuera del alcance  el garantizar que la impresión salga en los colores en que se visualiza..
        /// </summary>
        public static string Mensaje_Impresion {
            get {
                return ResourceManager.GetString("Mensaje_Impresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha realizado ningún cambio.
        /// </summary>
        public static string Ningun_Cambio {
            get {
                return ResourceManager.GetString("Ningun_Cambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el nivel de severidad.
        /// </summary>
        public static string Nivel_Severidad {
            get {
                return ResourceManager.GetString("Nivel_Severidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No acepto.
        /// </summary>
        public static string No_Acepto {
            get {
                return ResourceManager.GetString("No_Acepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No continuar.
        /// </summary>
        public static string No_Continuar {
            get {
                return ResourceManager.GetString("No_Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No podrá guardar sin escribir una justificación.
        /// </summary>
        public static string No_Escribir_Sin_Justificacion {
            get {
                return ResourceManager.GetString("No_Escribir_Sin_Justificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe procedimiento asociado en alguna de las superficies del diente.
        /// </summary>
        public static string No_Existe_Procedimiento_Asociado_Superficie_Diente {
            get {
                return ResourceManager.GetString("No_Existe_Procedimiento_Asociado_Superficie_Diente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen sesiones asociadas en plan de tratamiento.
        /// </summary>
        public static string No_Existen_Sessiones_Asociadas {
            get {
                return ResourceManager.GetString("No_Existen_Sessiones_Asociadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo tratamiento.
        /// </summary>
        public static string Nuevo_Tratamiento {
            get {
                return ResourceManager.GetString("Nuevo_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Factura.
        /// </summary>
        public static string Numero_Factura {
            get {
                return ResourceManager.GetString("Numero_Factura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de piezas dentales.
        /// </summary>
        public static string Numero_Piezas_Dentales {
            get {
                return ResourceManager.GetString("Numero_Piezas_Dentales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Sesiones.
        /// </summary>
        public static string Numero_Sesiones {
            get {
                return ResourceManager.GetString("Numero_Sesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Numero_Tratamiento {
            get {
                return ResourceManager.GetString("Numero_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontograma.
        /// </summary>
        public static string Odontograma {
            get {
                return ResourceManager.GetString("Odontograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontograma de evolución.
        /// </summary>
        public static string Odontograma_Evolucion {
            get {
                return ResourceManager.GetString("Odontograma_Evolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontograma inicial.
        /// </summary>
        public static string Odontograma_Inicial {
            get {
                return ResourceManager.GetString("Odontograma_Inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El odontograma se encuentra vacío.
        /// </summary>
        public static string Odontograma_Vacio {
            get {
                return ResourceManager.GetString("Odontograma_Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontogramas.
        /// </summary>
        public static string Odontogramas {
            get {
                return ResourceManager.GetString("Odontogramas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontólogo.
        /// </summary>
        public static string Odontologo {
            get {
                return ResourceManager.GetString("Odontologo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        public static string Paciente {
            get {
                return ResourceManager.GetString("Paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago por.
        /// </summary>
        public static string Pago_Por {
            get {
                return ResourceManager.GetString("Pago_Por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paso anterior.
        /// </summary>
        public static string Paso_Anterior {
            get {
                return ResourceManager.GetString("Paso_Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de tratamiento.
        /// </summary>
        public static string Plan_Tratamiento {
            get {
                return ResourceManager.GetString("Plan_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este plan de tratamiento está sujeto a cambios, sin previo aviso.
        /// </summary>
        public static string Plan_Tratamiento_Sin_Previo_Aviso {
            get {
                return ResourceManager.GetString("Plan_Tratamiento_Sin_Previo_Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestador.
        /// </summary>
        public static string Prestador {
            get {
                return ResourceManager.GetString("Prestador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El procedimiento ya ha sido realizado y no se puede eliminar.
        /// </summary>
        public static string Procedimiento_Realizado {
            get {
                return ResourceManager.GetString("Procedimiento_Realizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimientos.
        /// </summary>
        public static string Procedimientos {
            get {
                return ResourceManager.GetString("Procedimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen procedimientos asociados al plan de tratamiento.
        /// </summary>
        public static string Procedimientos_Asociados_Plan_Tratamiento {
            get {
                return ResourceManager.GetString("Procedimientos_Asociados_Plan_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimientos  Diagnósticos.
        /// </summary>
        public static string Procedimientos_Diagnosticos {
            get {
                return ResourceManager.GetString("Procedimientos_Diagnosticos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legalizado.
        /// </summary>
        public static string Procedimientos_Legalizados {
            get {
                return ResourceManager.GetString("Procedimientos_Legalizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen procedimientos no realizados por favor escriba una justificación..
        /// </summary>
        public static string Procedimientos_No_Realizados {
            get {
                return ResourceManager.GetString("Procedimientos_No_Realizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizado.
        /// </summary>
        public static string Procedimientos_Realizados {
            get {
                return ResourceManager.GetString("Procedimientos_Realizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional.
        /// </summary>
        public static string Profesional {
            get {
                return ResourceManager.GetString("Profesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la sesión.
        /// </summary>
        public static string Realice_Configuracion_Sesiones {
            get {
                return ResourceManager.GetString("Realice_Configuracion_Sesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de modificación.
        /// </summary>
        public static string Registro_Modificacion {
            get {
                return ResourceManager.GetString("Registro_Modificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere un usuario clasificador para abrir un nuevo odontograma.
        /// </summary>
        public static string Requiere_Clasificador {
            get {
                return ResourceManager.GetString("Requiere_Clasificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotar.
        /// </summary>
        public static string Rotar {
            get {
                return ResourceManager.GetString("Rotar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        public static string Saldo {
            get {
                return ResourceManager.GetString("Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un convenio.
        /// </summary>
        public static string Seleccionar_Convenio {
            get {
                return ResourceManager.GetString("Seleccionar_Convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar procedimiento.
        /// </summary>
        public static string Seleccionar_Procedimiento {
            get {
                return ResourceManager.GetString("Seleccionar_Procedimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necesita seleccionar un procedimiento o diagnóstico.
        /// </summary>
        public static string Seleccionar_Procedimiento_Diagnostico {
            get {
                return ResourceManager.GetString("Seleccionar_Procedimiento_Diagnostico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un elemento por favor.
        /// </summary>
        public static string Seleccione_Elemento {
            get {
                return ResourceManager.GetString("Seleccione_Elemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione el tipo de pago.
        /// </summary>
        public static string Seleccione_Tipo_Pago {
            get {
                return ResourceManager.GetString("Seleccione_Tipo_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión.
        /// </summary>
        public static string Sesion {
            get {
                return ResourceManager.GetString("Sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión/Cuotas.
        /// </summary>
        public static string Sesion_Cuotas {
            get {
                return ResourceManager.GetString("Sesion_Cuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programadas.
        /// </summary>
        public static string Sesiones_Programadas {
            get {
                return ResourceManager.GetString("Sesiones_Programadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizadas.
        /// </summary>
        public static string Sesiones_Realizadas {
            get {
                return ResourceManager.GetString("Sesiones_Realizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severidad.
        /// </summary>
        public static string Severidad {
            get {
                return ResourceManager.GetString("Severidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente paso.
        /// </summary>
        public static string Siguiente_Paso {
            get {
                return ResourceManager.GetString("Siguiente_Paso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar .
        /// </summary>
        public static string Sobreescribir {
            get {
                return ResourceManager.GetString("Sobreescribir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo lectura.
        /// </summary>
        public static string Solo_Lectura {
            get {
                return ResourceManager.GetString("Solo_Lectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superficie.
        /// </summary>
        public static string Superficie {
            get {
                return ResourceManager.GetString("Superficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distal.
        /// </summary>
        public static string Superficie_Distal {
            get {
                return ResourceManager.GetString("Superficie_Distal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incisal u oclusal.
        /// </summary>
        public static string Superficie_Incisal {
            get {
                return ResourceManager.GetString("Superficie_Incisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingual o palatina inferior.
        /// </summary>
        public static string Superficie_Lingual_Palatina_Inferior {
            get {
                return ResourceManager.GetString("Superficie_Lingual_Palatina_Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingual o palatina superior.
        /// </summary>
        public static string Superficie_Lingual_Palatina_Superior {
            get {
                return ResourceManager.GetString("Superficie_Lingual_Palatina_Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesial.
        /// </summary>
        public static string Superficie_Mesial {
            get {
                return ResourceManager.GetString("Superficie_Mesial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vestibular inferior.
        /// </summary>
        public static string Superficie_Vestibular_Inferior {
            get {
                return ResourceManager.GetString("Superficie_Vestibular_Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vestibular superior.
        /// </summary>
        public static string Superficie_Vestibular_Superior {
            get {
                return ResourceManager.GetString("Superficie_Vestibular_Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string Supernumerario {
            get {
                return ResourceManager.GetString("Supernumerario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supernumerario a la derecha.
        /// </summary>
        public static string Supernumerario_Derecha {
            get {
                return ResourceManager.GetString("Supernumerario_Derecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supernumerario a la izquierda.
        /// </summary>
        public static string Supernumerario_Izquierda {
            get {
                return ResourceManager.GetString("Supernumerario_Izquierda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tercero.
        /// </summary>
        public static string Tercero {
            get {
                return ResourceManager.GetString("Tercero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        public static string Texto {
            get {
                return ResourceManager.GetString("Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de sesión.
        /// </summary>
        public static string Tipo_Sesion {
            get {
                return ResourceManager.GetString("Tipo_Sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de tratamiento.
        /// </summary>
        public static string Tipo_Tratamiento {
            get {
                return ResourceManager.GetString("Tipo_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontología.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprueba plan de tratamiento.
        /// </summary>
        public static string Titulo_Aprueba_Plan_Tratamiento {
            get {
                return ResourceManager.GetString("Titulo_Aprueba_Plan_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar tratamiento.
        /// </summary>
        public static string Titulo_Cerrar_Tratamiento {
            get {
                return ResourceManager.GetString("Titulo_Cerrar_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los procedimientos han sido realizados, este tratamiento pasara a estado finalizado.
        /// </summary>
        public static string Todos_Procedimientos_Realizados {
            get {
                return ResourceManager.GetString("Todos_Procedimientos_Realizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratamientos.
        /// </summary>
        public static string Tratamientos {
            get {
                return ResourceManager.GetString("Tratamientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique que tenga procedimientos asociados y de click en siguiente.
        /// </summary>
        public static string Validacion_Procedimientos_Asociados {
            get {
                return ResourceManager.GetString("Validacion_Procedimientos_Asociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor cuota inicial.
        /// </summary>
        public static string Valor_Cuota_Inicial {
            get {
                return ResourceManager.GetString("Valor_Cuota_Inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Cuota/Sesión.
        /// </summary>
        public static string Valor_Cuota_Sesion {
            get {
                return ResourceManager.GetString("Valor_Cuota_Sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor paciente.
        /// </summary>
        public static string Valor_Paciente {
            get {
                return ResourceManager.GetString("Valor_Paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor pagado.
        /// </summary>
        public static string Valor_Pagado {
            get {
                return ResourceManager.GetString("Valor_Pagado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor procedimiento.
        /// </summary>
        public static string Valor_Procedimiento {
            get {
                return ResourceManager.GetString("Valor_Procedimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor total.
        /// </summary>
        public static string Valor_Total {
            get {
                return ResourceManager.GetString("Valor_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor total paciente.
        /// </summary>
        public static string Valor_Total_Paciente {
            get {
                return ResourceManager.GetString("Valor_Total_Paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor total procedimientos.
        /// </summary>
        public static string Valor_Total_Procedimientos {
            get {
                return ResourceManager.GetString("Valor_Total_Procedimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores.
        /// </summary>
        public static string Valores {
            get {
                return ResourceManager.GetString("Valores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string Ver_Detalle {
            get {
                return ResourceManager.GetString("Ver_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver imágenes.
        /// </summary>
        public static string Ver_Imagenes {
            get {
                return ResourceManager.GetString("Ver_Imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver odontograma.
        /// </summary>
        public static string Ver_Odontograma {
            get {
                return ResourceManager.GetString("Ver_Odontograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver tratamientos.
        /// </summary>
        public static string Ver_Tratamientos {
            get {
                return ResourceManager.GetString("Ver_Tratamientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe activo un tratamiento de este tipo.
        /// </summary>
        public static string Ya_Existe_Tratamiento_Tipo {
            get {
                return ResourceManager.GetString("Ya_Existe_Tratamiento_Tipo", resourceCulture);
            }
        }
    }
}
