//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnt.Panacea.Xap.Odontologia.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cnt.Panacea.Xap.Odontologia.Vm.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonado.
        /// </summary>
        public static string Abandonado {
            get {
                return ResourceManager.GetString("Abandonado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acepto.
        /// </summary>
        public static string Acepto {
            get {
                return ResourceManager.GetString("Acepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adicionar.
        /// </summary>
        public static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntar imágenes.
        /// </summary>
        public static string Adjuntar_Imagenes {
            get {
                return ResourceManager.GetString("Adjuntar_Imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar.
        /// </summary>
        public static string Aplicar {
            get {
                return ResourceManager.GetString("Aplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar a.
        /// </summary>
        public static string Aplicar_a {
            get {
                return ResourceManager.GetString("Aplicar_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar procedimientos.
        /// </summary>
        public static string Aplicar_Procedimientos {
            get {
                return ResourceManager.GetString("Aplicar_Procedimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desea aprobar la cotización.
        /// </summary>
        public static string Aprobar_Cotizacion {
            get {
                return ResourceManager.GetString("Aprobar_Cotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo salvado.
        /// </summary>
        public static string Archivo_Salvado {
            get {
                return ResourceManager.GetString("Archivo_Salvado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atrás.
        /// </summary>
        public static string Atras {
            get {
                return ResourceManager.GetString("Atras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aumentar.
        /// </summary>
        public static string Aumentar {
            get {
                return ResourceManager.GetString("Aumentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boca.
        /// </summary>
        public static string Boca {
            get {
                return ResourceManager.GetString("Boca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bodega.
        /// </summary>
        public static string Bodega {
            get {
                return ResourceManager.GetString("Bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar convenio.
        /// </summary>
        public static string Cambiar_Convenio {
            get {
                return ResourceManager.GetString("Cambiar_Convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambios sin guardar.
        /// </summary>
        public static string Cambios {
            get {
                return ResourceManager.GetString("Cambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El sistema ha identificado que ha realizado cambios que aun no se han guardado. ¿Desea continuar?.
        /// </summary>
        public static string Cambios_No_Guardados {
            get {
                return ResourceManager.GetString("Cambios_No_Guardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen campos sin diligenciar.
        /// </summary>
        public static string Campos_Sin_Diligenciar {
            get {
                return ResourceManager.GetString("Campos_Sin_Diligenciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        public static string Clave {
            get {
                return ResourceManager.GetString("Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De clic en siguiente por favor.
        /// </summary>
        public static string Click_Siguiente {
            get {
                return ResourceManager.GetString("Click_Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobro.
        /// </summary>
        public static string Cobro {
            get {
                return ResourceManager.GetString("Cobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un comprobante para la cotización.
        /// </summary>
        public static string Comprobante_Cotizacion {
            get {
                return ResourceManager.GetString("Comprobante_Cotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta.
        /// </summary>
        public static string Consulta {
            get {
                return ResourceManager.GetString("Consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string Continuar {
            get {
                return ResourceManager.GetString("Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convenio.
        /// </summary>
        public static string Convenio {
            get {
                return ResourceManager.GetString("Convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotización.
        /// </summary>
        public static string Cotizacion {
            get {
                return ResourceManager.GetString("Cotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cubre convenio.
        /// </summary>
        public static string Cubre_Convenio {
            get {
                return ResourceManager.GetString("Cubre_Convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuota inicial.
        /// </summary>
        public static string Cuota_Inicial {
            get {
                return ResourceManager.GetString("Cuota_Inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen datos asociados que aún no se han cargado por favor navegue a la pestana de plan de tratamiento y después al plan de evolución..
        /// </summary>
        public static string Datos_Odontograma_Evolucion {
            get {
                return ResourceManager.GetString("Datos_Odontograma_Evolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir plan tratamiento.
        /// </summary>
        public static string Definir_Plan_Tratamiento {
            get {
                return ResourceManager.GetString("Definir_Plan_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        public static string Descargar {
            get {
                return ResourceManager.GetString("Descargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deshacer.
        /// </summary>
        public static string Deshacer {
            get {
                return ResourceManager.GetString("Deshacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este diagnóstico o procedimiento ya se encuentra asociado a este elemento.
        /// </summary>
        public static string Diagnostico_Procedimiento_Asignado {
            get {
                return ResourceManager.GetString("Diagnostico_Procedimiento_Asignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagnósticos.
        /// </summary>
        public static string Diagnosticos {
            get {
                return ResourceManager.GetString("Diagnosticos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen diagnósticos sin procedimiento asociado.
        /// </summary>
        public static string Diagnosticos_Sin_Procedimiento_Asociado {
            get {
                return ResourceManager.GetString("Diagnosticos_Sin_Procedimiento_Asociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Diente {
            get {
                return ResourceManager.GetString("Diente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diente.
        /// </summary>
        public static string Dientes {
            get {
                return ResourceManager.GetString("Dientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supera la cantidad de procedimientos en la sesión.
        /// </summary>
        public static string Error_Cantidad_Procedimientos {
            get {
                return ResourceManager.GetString("Error_Cantidad_Procedimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supera la cantidad de sesiones.
        /// </summary>
        public static string Error_Cantidad_Sesiones {
            get {
                return ResourceManager.GetString("Error_Cantidad_Sesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De clic en siguiente antes de guardar.
        /// </summary>
        public static string Error_Elementos_PlanTratamiento {
            get {
                return ResourceManager.GetString("Error_Elementos_PlanTratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen seleccionada presenta errores.
        /// </summary>
        public static string Error_Imagen {
            get {
                return ResourceManager.GetString("Error_Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de piezas debe ser un dato númerico mayor de 0.
        /// </summary>
        public static string Error_Mensaje_Piezas {
            get {
                return ResourceManager.GetString("Error_Mensaje_Piezas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El numero de dientes no puede ser negativo.
        /// </summary>
        public static string Error_Mensaje_Piezas2 {
            get {
                return ResourceManager.GetString("Error_Mensaje_Piezas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No esta cubierto por el convenio.
        /// </summary>
        public static string Error_No_Cubre_Convenio1 {
            get {
                return ResourceManager.GetString("Error_No_Cubre_Convenio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro :.
        /// </summary>
        public static string Error_No_Cubre_Convenio2 {
            get {
                return ResourceManager.GetString("Error_No_Cubre_Convenio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las sesiones no están configuradas correctamente.
        /// </summary>
        public static string Error_Sesiones {
            get {
                return ResourceManager.GetString("Error_Sesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las sesiones deben asignarse consecutivamente.
        /// </summary>
        public static string Error_Sesiones_Consecutivas {
            get {
                return ResourceManager.GetString("Error_Sesiones_Consecutivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No podrá realizar ninguna acción en el odontograma de tratamiento hasta que tenga diagnósticos en el odontograma inicial.
        /// </summary>
        public static string Error_Solo_Procedimientos {
            get {
                return ResourceManager.GetString("Error_Solo_Procedimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la especialidad a cada procedimiento..
        /// </summary>
        public static string ErrorEspecialidad {
            get {
                return ResourceManager.GetString("ErrorEspecialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especialidad.
        /// </summary>
        public static string Especialidad {
            get {
                return ResourceManager.GetString("Especialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del tratamiento.
        /// </summary>
        public static string Estado_Tratamiento {
            get {
                return ResourceManager.GetString("Estado_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura.
        /// </summary>
        public static string Factura {
            get {
                return ResourceManager.GetString("Factura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha final.
        /// </summary>
        public static string Fecha_Final {
            get {
                return ResourceManager.GetString("Fecha_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha inicial.
        /// </summary>
        public static string Fecha_Inicial {
            get {
                return ResourceManager.GetString("Fecha_Inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha inicio.
        /// </summary>
        public static string Fecha_Inicio_Tratamiento {
            get {
                return ResourceManager.GetString("Fecha_Inicio_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalidad.
        /// </summary>
        public static string Finalidad_Procedimiento {
            get {
                return ResourceManager.GetString("Finalidad_Procedimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizado.
        /// </summary>
        public static string Finalizado {
            get {
                return ResourceManager.GetString("Finalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar tratamiento.
        /// </summary>
        public static string Finalizar_Tratamiento {
            get {
                return ResourceManager.GetString("Finalizar_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de pago.
        /// </summary>
        public static string Forma_Pago {
            get {
                return ResourceManager.GetString("Forma_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se genera el plan de tratamiento No..
        /// </summary>
        public static string Genero_Plan_Tratamiento1 {
            get {
                return ResourceManager.GetString("Genero_Plan_Tratamiento1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de tratamiento.
        /// </summary>
        public static string Genero_Plan_Tratamiento2 {
            get {
                return ResourceManager.GetString("Genero_Plan_Tratamiento2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ortodoncia.
        /// </summary>
        public static string Genero_Plan_Tratamiento3 {
            get {
                return ResourceManager.GetString("Genero_Plan_Tratamiento3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se genera cotización No..
        /// </summary>
        public static string Genero_Plan_Tratamiento4 {
            get {
                return ResourceManager.GetString("Genero_Plan_Tratamiento4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar en el equipo.
        /// </summary>
        public static string Guardar_Equipo {
            get {
                return ResourceManager.GetString("Guardar_Equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Odontograma guardado correctamente.
        /// </summary>
        public static string Guardar_Odontograma {
            get {
                return ResourceManager.GetString("Guardar_Odontograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Higienista.
        /// </summary>
        public static string Higienista {
            get {
                return ResourceManager.GetString("Higienista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial odontograma.
        /// </summary>
        public static string Historial_Odontograma {
            get {
                return ResourceManager.GetString("Historial_Odontograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        public static string Imagen {
            get {
                return ResourceManager.GetString("Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        public static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Odontograma inicial.
        /// </summary>
        public static string Imprimir_Odontograma_Inicial {
            get {
                return ResourceManager.GetString("Imprimir_Odontograma_Inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Odontograma plan de tratamiento.
        /// </summary>
        public static string Imprimir_Odontograma_Plan_Tratamiento {
            get {
                return ResourceManager.GetString("Imprimir_Odontograma_Plan_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informes.
        /// </summary>
        public static string Informes {
            get {
                return ResourceManager.GetString("Informes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insumos.
        /// </summary>
        public static string Insumos {
            get {
                return ResourceManager.GetString("Insumos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requiere una justificación para guardar en el sistema..
        /// </summary>
        public static string Justificacion_Guardar_Sistema {
            get {
                return ResourceManager.GetString("Justificacion_Guardar_Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máximo número de procedimientos por sesión.
        /// </summary>
        public static string Maximo_Procedimientos_Por_Sesion {
            get {
                return ResourceManager.GetString("Maximo_Procedimientos_Por_Sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden realizar mas procedimientos en esta sesión.
        /// </summary>
        public static string Maximo_Procedimientos_Sesion {
            get {
                return ResourceManager.GetString("Maximo_Procedimientos_Sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede insertar máximo 10 piezas dentales supernumerarias.
        /// </summary>
        public static string Maximo_Supernumerarios {
            get {
                return ResourceManager.GetString("Maximo_Supernumerarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este procedimiento no se encuentra cubierto por el convenio.
        /// </summary>
        public static string Mensaje_Convenio {
            get {
                return ResourceManager.GetString("Mensaje_Convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta fuera del alcance  el garantizar que la impresión salga en los colores en que se visualiza..
        /// </summary>
        public static string Mensaje_Impresion {
            get {
                return ResourceManager.GetString("Mensaje_Impresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha realizado ningún cambio.
        /// </summary>
        public static string Ningun_Cambio {
            get {
                return ResourceManager.GetString("Ningun_Cambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el nivel de severidad.
        /// </summary>
        public static string Nivel_Severidad {
            get {
                return ResourceManager.GetString("Nivel_Severidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No acepto.
        /// </summary>
        public static string No_Acepto {
            get {
                return ResourceManager.GetString("No_Acepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No continuar.
        /// </summary>
        public static string No_Continuar {
            get {
                return ResourceManager.GetString("No_Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No podrá guardar sin escribir una justificación.
        /// </summary>
        public static string No_Escribir_Sin_Justificacion {
            get {
                return ResourceManager.GetString("No_Escribir_Sin_Justificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe procedimiento asociado en alguna de las superficies del diente.
        /// </summary>
        public static string No_Existe_Procedimiento_Asociado_Superficie_Diente {
            get {
                return ResourceManager.GetString("No_Existe_Procedimiento_Asociado_Superficie_Diente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen sesiones asociadas en plan de tratamiento.
        /// </summary>
        public static string No_Existen_Sessiones_Asociadas {
            get {
                return ResourceManager.GetString("No_Existen_Sessiones_Asociadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo tratamiento.
        /// </summary>
        public static string Nuevo_Tratamiento {
            get {
                return ResourceManager.GetString("Nuevo_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Factura.
        /// </summary>
        public static string Numero_Factura {
            get {
                return ResourceManager.GetString("Numero_Factura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de piezas dentales.
        /// </summary>
        public static string Numero_Piezas_Dentales {
            get {
                return ResourceManager.GetString("Numero_Piezas_Dentales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Sesiones.
        /// </summary>
        public static string Numero_Sesiones {
            get {
                return ResourceManager.GetString("Numero_Sesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número.
        /// </summary>
        public static string Numero_Tratamiento {
            get {
                return ResourceManager.GetString("Numero_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Odontograma.
        /// </summary>
        public static string Odontograma {
            get {
                return ResourceManager.GetString("Odontograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Odontograma de evolución.
        /// </summary>
        public static string Odontograma_Evolucion {
            get {
                return ResourceManager.GetString("Odontograma_Evolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Odontograma inicial.
        /// </summary>
        public static string Odontograma_Inicial {
            get {
                return ResourceManager.GetString("Odontograma_Inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El odontograma se encuentra vacío.
        /// </summary>
        public static string Odontograma_Vacio {
            get {
                return ResourceManager.GetString("Odontograma_Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Odontogramas.
        /// </summary>
        public static string Odontogramas {
            get {
                return ResourceManager.GetString("Odontogramas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Odontólogo.
        /// </summary>
        public static string Odontologo {
            get {
                return ResourceManager.GetString("Odontologo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paciente.
        /// </summary>
        public static string Paciente {
            get {
                return ResourceManager.GetString("Paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago por.
        /// </summary>
        public static string Pago_Por {
            get {
                return ResourceManager.GetString("Pago_Por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso anterior.
        /// </summary>
        public static string Paso_Anterior {
            get {
                return ResourceManager.GetString("Paso_Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan de tratamiento.
        /// </summary>
        public static string Plan_Tratamiento {
            get {
                return ResourceManager.GetString("Plan_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este plan de tratamiento está sujeto a cambios, sin previo aviso.
        /// </summary>
        public static string Plan_Tratamiento_Sin_Previo_Aviso {
            get {
                return ResourceManager.GetString("Plan_Tratamiento_Sin_Previo_Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prestador.
        /// </summary>
        public static string Prestador {
            get {
                return ResourceManager.GetString("Prestador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El procedimiento ya ha sido realizado y no se puede eliminar.
        /// </summary>
        public static string Procedimiento_Realizado {
            get {
                return ResourceManager.GetString("Procedimiento_Realizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedimientos.
        /// </summary>
        public static string Procedimientos {
            get {
                return ResourceManager.GetString("Procedimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen procedimientos asociados al plan de tratamiento.
        /// </summary>
        public static string Procedimientos_Asociados_Plan_Tratamiento {
            get {
                return ResourceManager.GetString("Procedimientos_Asociados_Plan_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedimientos  Diagnósticos.
        /// </summary>
        public static string Procedimientos_Diagnosticos {
            get {
                return ResourceManager.GetString("Procedimientos_Diagnosticos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Legalizado.
        /// </summary>
        public static string Procedimientos_Legalizados {
            get {
                return ResourceManager.GetString("Procedimientos_Legalizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen procedimientos no realizados por favor escriba una justificación..
        /// </summary>
        public static string Procedimientos_No_Realizados {
            get {
                return ResourceManager.GetString("Procedimientos_No_Realizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizado.
        /// </summary>
        public static string Procedimientos_Realizados {
            get {
                return ResourceManager.GetString("Procedimientos_Realizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profesional.
        /// </summary>
        public static string Profesional {
            get {
                return ResourceManager.GetString("Profesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la sesión.
        /// </summary>
        public static string Realice_Configuracion_Sesiones {
            get {
                return ResourceManager.GetString("Realice_Configuracion_Sesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de modificación.
        /// </summary>
        public static string Registro_Modificacion {
            get {
                return ResourceManager.GetString("Registro_Modificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requiere un usuario clasificador para abrir un nuevo odontograma.
        /// </summary>
        public static string Requiere_Clasificador {
            get {
                return ResourceManager.GetString("Requiere_Clasificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotar.
        /// </summary>
        public static string Rotar {
            get {
                return ResourceManager.GetString("Rotar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saldo.
        /// </summary>
        public static string Saldo {
            get {
                return ResourceManager.GetString("Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un convenio.
        /// </summary>
        public static string Seleccionar_Convenio {
            get {
                return ResourceManager.GetString("Seleccionar_Convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar procedimiento.
        /// </summary>
        public static string Seleccionar_Procedimiento {
            get {
                return ResourceManager.GetString("Seleccionar_Procedimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesita seleccionar un procedimiento o diagnóstico.
        /// </summary>
        public static string Seleccionar_Procedimiento_Diagnostico {
            get {
                return ResourceManager.GetString("Seleccionar_Procedimiento_Diagnostico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un elemento por favor.
        /// </summary>
        public static string Seleccione_Elemento {
            get {
                return ResourceManager.GetString("Seleccione_Elemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor seleccione el tipo de pago.
        /// </summary>
        public static string Seleccione_Tipo_Pago {
            get {
                return ResourceManager.GetString("Seleccione_Tipo_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesión.
        /// </summary>
        public static string Sesion {
            get {
                return ResourceManager.GetString("Sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesión/Cuotas.
        /// </summary>
        public static string Sesion_Cuotas {
            get {
                return ResourceManager.GetString("Sesion_Cuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programadas.
        /// </summary>
        public static string Sesiones_Programadas {
            get {
                return ResourceManager.GetString("Sesiones_Programadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizadas.
        /// </summary>
        public static string Sesiones_Realizadas {
            get {
                return ResourceManager.GetString("Sesiones_Realizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Severidad.
        /// </summary>
        public static string Severidad {
            get {
                return ResourceManager.GetString("Severidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente paso.
        /// </summary>
        public static string Siguiente_Paso {
            get {
                return ResourceManager.GetString("Siguiente_Paso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar .
        /// </summary>
        public static string Sobreescribir {
            get {
                return ResourceManager.GetString("Sobreescribir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo lectura.
        /// </summary>
        public static string Solo_Lectura {
            get {
                return ResourceManager.GetString("Solo_Lectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superficie.
        /// </summary>
        public static string Superficie {
            get {
                return ResourceManager.GetString("Superficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distal.
        /// </summary>
        public static string Superficie_Distal {
            get {
                return ResourceManager.GetString("Superficie_Distal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incisal u oclusal.
        /// </summary>
        public static string Superficie_Incisal {
            get {
                return ResourceManager.GetString("Superficie_Incisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lingual o palatina inferior.
        /// </summary>
        public static string Superficie_Lingual_Palatina_Inferior {
            get {
                return ResourceManager.GetString("Superficie_Lingual_Palatina_Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lingual o palatina superior.
        /// </summary>
        public static string Superficie_Lingual_Palatina_Superior {
            get {
                return ResourceManager.GetString("Superficie_Lingual_Palatina_Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mesial.
        /// </summary>
        public static string Superficie_Mesial {
            get {
                return ResourceManager.GetString("Superficie_Mesial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vestibular inferior.
        /// </summary>
        public static string Superficie_Vestibular_Inferior {
            get {
                return ResourceManager.GetString("Superficie_Vestibular_Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vestibular superior.
        /// </summary>
        public static string Superficie_Vestibular_Superior {
            get {
                return ResourceManager.GetString("Superficie_Vestibular_Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a S.
        /// </summary>
        public static string Supernumerario {
            get {
                return ResourceManager.GetString("Supernumerario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supernumerario a la derecha.
        /// </summary>
        public static string Supernumerario_Derecha {
            get {
                return ResourceManager.GetString("Supernumerario_Derecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supernumerario a la izquierda.
        /// </summary>
        public static string Supernumerario_Izquierda {
            get {
                return ResourceManager.GetString("Supernumerario_Izquierda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tercero.
        /// </summary>
        public static string Tercero {
            get {
                return ResourceManager.GetString("Tercero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        public static string Texto {
            get {
                return ResourceManager.GetString("Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de sesión.
        /// </summary>
        public static string Tipo_Sesion {
            get {
                return ResourceManager.GetString("Tipo_Sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de tratamiento.
        /// </summary>
        public static string Tipo_Tratamiento {
            get {
                return ResourceManager.GetString("Tipo_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Odontología.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprueba plan de tratamiento.
        /// </summary>
        public static string Titulo_Aprueba_Plan_Tratamiento {
            get {
                return ResourceManager.GetString("Titulo_Aprueba_Plan_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar tratamiento.
        /// </summary>
        public static string Titulo_Cerrar_Tratamiento {
            get {
                return ResourceManager.GetString("Titulo_Cerrar_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los procedimientos han sido realizados, este tratamiento pasara a estado finalizado.
        /// </summary>
        public static string Todos_Procedimientos_Realizados {
            get {
                return ResourceManager.GetString("Todos_Procedimientos_Realizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tratamientos.
        /// </summary>
        public static string Tratamientos {
            get {
                return ResourceManager.GetString("Tratamientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifique que tenga procedimientos asociados y de click en siguiente.
        /// </summary>
        public static string Validacion_Procedimientos_Asociados {
            get {
                return ResourceManager.GetString("Validacion_Procedimientos_Asociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor cuota inicial.
        /// </summary>
        public static string Valor_Cuota_Inicial {
            get {
                return ResourceManager.GetString("Valor_Cuota_Inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Cuota/Sesión.
        /// </summary>
        public static string Valor_Cuota_Sesion {
            get {
                return ResourceManager.GetString("Valor_Cuota_Sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor paciente.
        /// </summary>
        public static string Valor_Paciente {
            get {
                return ResourceManager.GetString("Valor_Paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor pagado.
        /// </summary>
        public static string Valor_Pagado {
            get {
                return ResourceManager.GetString("Valor_Pagado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor procedimiento.
        /// </summary>
        public static string Valor_Procedimiento {
            get {
                return ResourceManager.GetString("Valor_Procedimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor total.
        /// </summary>
        public static string Valor_Total {
            get {
                return ResourceManager.GetString("Valor_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor total paciente.
        /// </summary>
        public static string Valor_Total_Paciente {
            get {
                return ResourceManager.GetString("Valor_Total_Paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor total procedimientos.
        /// </summary>
        public static string Valor_Total_Procedimientos {
            get {
                return ResourceManager.GetString("Valor_Total_Procedimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valores.
        /// </summary>
        public static string Valores {
            get {
                return ResourceManager.GetString("Valores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string Ver_Detalle {
            get {
                return ResourceManager.GetString("Ver_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver imágenes.
        /// </summary>
        public static string Ver_Imagenes {
            get {
                return ResourceManager.GetString("Ver_Imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver odontograma.
        /// </summary>
        public static string Ver_Odontograma {
            get {
                return ResourceManager.GetString("Ver_Odontograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver tratamientos.
        /// </summary>
        public static string Ver_Tratamientos {
            get {
                return ResourceManager.GetString("Ver_Tratamientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe activo un tratamiento de este tipo.
        /// </summary>
        public static string Ya_Existe_Tratamiento_Tipo {
            get {
                return ResourceManager.GetString("Ya_Existe_Tratamiento_Tipo", resourceCulture);
            }
        }
    }
}
